### ISSUE TITLE
updated link

### ISSUE THREAD

**Issue by eladkarako** [Magnus010/PiHole#1]
@Magnus010 
here is the updated link, <a href="http://hosts.eladkarako.com/">from the HOSTS repository</a> (repository got renamed).

<pre>
https://raw.githubusercontent.com/eladkarako/hosts.eladkarako.com/master/_raw__hosts.txt

<sub>also available...
HOSTS (HOSTS format)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_with_localhost.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0_with_localhost.txt

HOSTS (AdBlock format)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock.txt

AdBlock lists
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block_inline_script.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_hide.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_style_inject.txt
</sub>
</pre>

Ps.
if you generate a <code>HOSTS</code> file,
you might want to add (at the top):
<pre>
127.0.0.1 localhost
127.0.0.1 loopback
::1       localhost
</pre>
<sub>which will then make it Windows/Linux(/Android) compatible,<br/>also, it users can download the file and use it without the need of pre-editing it.</sub>

**Comment by Magnus010** [comment]
Updated, thanks!
